name: Docker Image CI

on: 
release: 
types: [push]

jobs: 
build: 
runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag benkey0/aria2docker:latest
        - name: Push the latest Docker image
          run: docker push benkey0/aria2docker:latest
